AWSTemplateFormatVersion: '2010-09-09'
Description: >
  IAM User Group and Policies for CI/CD and GitHub Actions to deploy Lambda and CloudFormation.

Resources:
  CICDUserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: cicd-github-actions-group

  CICDPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: cicd-github-actions-policy
      Groups:
        - !Ref CICDUserGroup
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:DescribeStackEvents
              - cloudformation:GetTemplate
              - cloudformation:ValidateTemplate
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:DeleteChangeSet
              - lambda:CreateFunction
              - lambda:UpdateFunctionCode
              - lambda:UpdateFunctionConfiguration
              - lambda:DeleteFunction
              - lambda:GetFunction
              - lambda:ListFunctions
              - lambda:AddPermission
              - lambda:RemovePermission
              - iam:PassRole
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
              - s3:DeleteObject
              - apigateway:POST
              - apigateway:PUT
              - apigateway:GET
              - apigateway:DELETE
              - apigateway:PATCH
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - appconfig:GetConfiguration
              - appconfig:StartConfigurationSession
              - appconfig:GetLatestConfiguration
              - appconfig:ListApplications
              - appconfig:ListEnvironments
              - appconfig:ListConfigurationProfiles
              - appconfig:ListHostedConfigurationVersions
              - cloudwatch:PutMetricData
            Resource: '*'

  CICDUser:
    Type: AWS::IAM::User
    Properties:
      UserName: cicd-github-actions-user
      Groups:
        - !Ref CICDUserGroup

  CICDUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref CICDUser

Outputs:
  CICDUserGroupName:
    Description: Name of the CI/CD IAM User Group
    Value: !Ref CICDUserGroup
  CICDPolicyName:
    Description: Name of the CI/CD IAM Policy
    Value: !Ref CICDPolicy
  CICDUserName:
    Description: Name of the CI/CD IAM User
    Value: !Ref CICDUser
  CICDUserAccessKeyId:
    Description: Access Key ID for the CI/CD IAM User
    Value: !Ref CICDUserAccessKey
  CICDUserSecretAccessKey:
    Description: Secret Access Key for the CI/CD IAM User
    Value: !GetAtt CICDUserAccessKey.SecretAccessKey
